# Generated by Django 4.2.1 on 2024-03-06 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bashgah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_bashgah', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('coaches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sport_field', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('code_melli', models.CharField(max_length=255)),
                ('history_of_specific_disease', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('bashgah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport.bashgah')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bashgah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sport.bashgah')),
                ('players', models.ManyToManyField(blank=True, to='sport.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tornoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date_of_register', models.DateField()),
                ('end_date_of_register', models.DateField()),
                ('sport_field', models.CharField(max_length=55)),
                ('tornoment_status', models.CharField(choices=[('not_started', 'شروع نشده'), ('registering', 'قابل ثبت نام'), ('on_performing', 'در حال برگزاری'), ('end_of_tornoment', 'اتمام تورنومنت')], default='not_started', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tornoments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_competition', models.DateTimeField()),
                ('location', models.TextField()),
                ('competition_status', models.CharField(choices=[('not_started', 'شروع نشده'), ('on_performing', 'در حال برگزاری'), ('end', 'اتمام مسابقه')], default='not_started', max_length=20)),
                ('first_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_as_first_team', to='sport.team')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loser', to='sport.team')),
                ('second_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_as_second_team', to='sport.team')),
                ('winer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winer', to='sport.team')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_competition', models.DateTimeField()),
                ('competition_status', models.CharField(choices=[('not_started', 'شروع نشده'), ('on_performing', 'در حال برگزاری'), ('end', 'اتمام مسابقه')], default='not_started', max_length=20)),
                ('location', models.TextField()),
                ('players', models.ManyToManyField(to='sport.player')),
            ],
        ),
    ]
