# Generated by Django 4.2.1 on 2024-03-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_team_bashgah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bashgah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport.bashgah'),
        ),
    ]
