# Generated by Django 4.2.1 on 2024-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_player_bashgah'),
    ]

    operations = [
        migrations.AddField(
            model_name='bashgah',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bashgah',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
