# Generated by Django 4.2.1 on 2024-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_bashgah_description_bashgah_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredInTheMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
